kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: podprompt
nodes:
  # Control plane
  - role: control-plane
    kubeadmConfigPatches:
    - |
      kind: InitConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "ingress-ready=true"
    extraPortMappings:
    - containerPort: 80
      hostPort: 80
      protocol: TCP
    - containerPort: 443
      hostPort: 443
      protocol: TCP
  
  # Workers
  - role: worker
    labels:
      workload-type: frontend
  
  - role: worker
    labels:
      workload-type: backend
  
  - role: worker
    labels:
      workload-type: datascience
  
  - role: worker
    labels:
      workload-type: operational